tracking/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('', views.login_view, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('violation/', views.violation_form, name='violation_form'),  # For new violation
    path('violation/<int:id>/', views.violation_form, name='violation_edit'),  # For editing an existing violation
    path('violations/', views.violation_list, name='violation_list'),  # To view the list of violations
    path('api/violations/', views.ViolationCreateAPIView.as_view(), name='violation_create_api'),

    # Add other paths here if needed
]

violations/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tracking/", include("tracking.urls")),
    path('', include("tracking.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracking/models.py
from django.db import models

class Violation(models.Model):
    date = models.DateField()
    violation_type = models.CharField(max_length=100)
    fine_collected = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    vehicle_number = models.CharField(max_length=20)
    officer_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='violations/', blank=True, null=True)  # Add this field for the image

    def __str__(self):
        return f"{self.violation_type} - {self.vehicle_number}"


class ViolationType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

tracking/forms.py
# forms.py
from django import forms
from .models import Violation, ViolationType
from django.utils import timezone

class LoginForm(forms.Form):
    username = forms.CharField(
        label="Username",
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )

class ViolationForm(forms.ModelForm):
    class Meta:
        model = Violation
        fields = ['date', 'violation_type', 'fine_collected', 'description', 'vehicle_number', 'officer_name', 'image']
        widgets = {
            'officer_name': forms.HiddenInput(),
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

    violation_type = forms.ModelChoiceField(queryset=ViolationType.objects.all(), empty_label="Select Violation Type")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ViolationForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['officer_name'].initial = user.get_full_name()
        self.fields['date'].initial = timezone.now().date()

tracking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .forms import LoginForm
from django.contrib.auth import logout
from .models import Violation
from .forms import ViolationForm
from django.core.serializers import serialize
from django.db.models import Count
from django.utils import timezone
import json
from datetime import timedelta
from django.db.models import Sum, Count
from rest_framework import status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.views import APIView
from .serializers import ViolationSerializer


def dashboard(request):
    today = timezone.now().date()
    last_week = today - timezone.timedelta(days=7)

    # Aggregate data for violations per date and violation type
    violations = (Violation.objects
                  .filter(date__range=[last_week, today])
                  .values('violation_type', 'date')
                  .annotate(count=Count('id'))
                  .order_by('date'))

    violation_list = []
    for violation in violations:
        violation_list.append({
            'violation_type': violation['violation_type'],
            'date': violation['date'].strftime('%Y-%m-%d'),  # Convert date to string
            'count': violation['count']
        })
    end_date = timezone.now().date()
    start_date = end_date - timedelta(days=6)  # Last 7 days

    fine_trend = (
        Violation.objects.filter(date__range=[start_date, end_date])
        .values('date')
        .annotate(total_fine=Sum('fine_collected'))
        .order_by('date')
    )

    # Convert to JSON serializable format
    fine_trend_data = list(fine_trend)

    # Serialize the data to JSON
    violation_df_json = json.dumps(violation_list)

    total_fine_collected = \
    Violation.objects.filter(date__range=[start_date, end_date]).aggregate(Sum('fine_collected'))[
        'fine_collected__sum'] or 0

    # Query the total number of violations for the last 7 days
    total_violations = Violation.objects.filter(date__range=[start_date, end_date]).count()
    total_vehicles = Violation.objects.filter(date__range=[start_date, end_date]).aggregate(
        distinct_vehicle_count=Count('vehicle_number', distinct=True)
    )['distinct_vehicle_count'] or 0



    violation = Violation.objects.all()
    context = {
        'violation_df_json': violation_df_json,
        'violations': violation,
        'fine_trend_json': json.dumps(fine_trend_data, default=str),
        'total_fine_collected': total_fine_collected,
        'total_violations': total_violations,
        'total_vehicles': total_vehicles

    }
    return render(request, 'home/index.html', context)


def logout_view(request):
    logout(request)
    return redirect('login')

def login_view(request):
    form = LoginForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')  # Redirect to a home or dashboard page
            else:
                messages.error(request, 'Invalid username or password.')

    return render(request, 'accounts/login.html', {'form': form})


# View to create and edit violations
def violation_form(request, id=None):
    if id:
        violation = get_object_or_404(Violation, id=id)
    else:
        violation = None

    if request.method == 'POST':
        form = ViolationForm(request.POST, request.FILES, user=request.user)  # Pass the logged-in user to the form
        print("comimghere")
        if form.is_valid():
            form.save()  # Save the form
            return redirect('dashboard')  # Redirect to a list or confirmation page after submission
        else:
            print(form.errors)
    else:
        form = ViolationForm(user=request.user)
        form.fields['officer_name'].initial = request.user.username

    context = {
        'form': form,
        'current_violation': violation
    }

    return render(request, 'home/violation_form.html', context)


# View to list all violations
def violation_list(request):
    violations = Violation.objects.all()
    return render(request, 'violation_list.html', {'violations': violations})


class ViolationCreateAPIView(APIView):
    parser_classes = [MultiPartParser, FormParser]  # Support file uploads

    def post(self, request, *args, **kwargs):
        serializer = ViolationSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save()  # Save the violation data
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Login
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              {% if messages %}
                {% for message in messages %}
                    <span class="text-danger">{{ message }}</span>
                {% endfor %}
              {% else %}
                  Add your credentials
              {% endif %}
          </h6>

          <br />

          <form role="form" method="post" action="{% url 'login' %}">

            {% csrf_token %}

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Username</label>
                  {{ form.username }}
                </div>
              </div>
            </div>

            <br />

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Password</label>
                  {{ form.password }}
                </div>
              </div>
            </div>

            <br />

            <button type="submit" name="login" class="btn btn-primary pull-left">Login</button>

            &nbsp; &nbsp;

            <div class="clearfix"></div>

          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Create Account
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              {% if msg %}
                <span class="text-danger">{{ msg | safe }}</span>
              {% else %}
                Add your credentials
              {% endif %}  
          </h6>
          
          <br />

          {% if success %}

            <p class="">
              Please <a href="{% url 'login' %}" class="text-black text-small">authenticate</a> using the new account.
            </p>  

          {% else %}
            <form role="form" method="post" action="">
                
              {% csrf_token %} 

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Username</label>
                    {{ form.username }}
                  </div>
                </div>
              </div>
              <span class="text-danger">{{ form.username.errors }}</span>

              <br />

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Email</label>
                    {{ form.email }}
                  </div>
                </div>
              </div>
              <span class="text-danger">{{ form.email.errors }}</span>

              <br />

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Password</label>
                    {{ form.password1 }}
                  </div>
                </div>
              </div>
              <span class="text-danger">{{ form.password1.errors }}</span>

              <br />

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Password Check</label>
                    {{ form.password2 }}
                  </div>
                </div>
              </div>
              <span class="text-danger">{{ form.password2.errors }}</span>

              <br />

              <button type="submit" name="register" class="btn btn-primary pull-left">Register</button>

              &nbsp; &nbsp; 
              <span class="pull-right">
                Have an account? <a href="{% url 'login' %}" class="text-primary">Login</a>
              </span>

              <div class="clearfix"></div>

            </form>
          {% endif %}

        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Login
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              Add your credentials
          </h6>
          
          <br />

          <form role="form" action="/">
              
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Username</label>
                  <input type="text" class="form-control" placeholder="Username">
                </div>
              </div>
            </div>

            <br />

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Password</label>
                  <input type="password" class="form-control" placeholder="Password">
                </div>
              </div>
            </div>

            <br />

            <button type="submit" name="login" class="btn btn-primary pull-left">Login</button>

            &nbsp; &nbsp; 
            <span class="pull-right">
              Don't have an account? <a href="/register.html" class="text-primary">Create</a>
            </span>

            <div class="clearfix"></div>

          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/page-403.html
{% extends "layouts/base.html" %}

{% block title %} Page 403 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 403</h6>
                    <h4 class="card-title">
                        Access Denied - Please authenticate
                    </h4>
                    <a href="{% url 'login' %}" class="btn btn-primary btn-round">LOGIN</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/page-404.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 404</h6>
                    <h4 class="card-title">
                        Page not found
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/page-500.html
{% extends "layouts/base.html" %}

{% block title %} Page 500 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 500</h6>
                    <h4 class="card-title">
                        Internal Server Error
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content 
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/register.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Create Account
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              Add your credentials
          </h6>
          
          <br />
          <form role="form" action="/">

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Username</label>
                  <input type="text" class="form-control" placeholder="Username">
                </div>
              </div>
            </div>

            <br />
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Email</label>
                  <input type="email" class="form-control" placeholder="Email">
                </div>
              </div>
            </div>

            <br />
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Password</label>
                  <input type="password" class="form-control" placeholder="Password">
                </div>
              </div>
            </div>

            <br />
            <button name="register" class="btn btn-primary pull-left">Register</button>

            &nbsp; &nbsp; 
            <span class="pull-right">
              Have an account? <a href="/login.html" class="text-primary">Login</a>
            </span>

            <div class="clearfix"></div>

          </form>

        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/ui-icons.html
{% extends "layouts/base.html" %}

{% block title %} UI Icons {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="container-fluid">
            <div class="card card-plain">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Material Design Icons</h4>
                <p class="card-category">Handcrafted by our friends from
                  <a target="_blank" href="https://design.google.com/icons/">Google</a>
                </p>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="card-body">
                    <div class="iframe-container d-none d-lg-block">
                      <iframe src="https://design.google.com/icons/">
                        <p>Your browser does not support iframes.</p>
                      </iframe>
                    </div>
                    <div class="col-md-12 d-none d-sm-block d-md-block d-lg-none d-block d-sm-none text-center ml-auto mr-auto">
                      <h5>The icons are visible on Desktop mode inside an iframe. Since the iframe is not working on Mobile and Tablets please visit the icons on their original page on Google. Check the
                        <a href="https://design.google.com/icons/" target="_blank">Material Icons</a>
                      </h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/ui-maps.html
{% extends "layouts/base.html" %}

{% block title %} Maps {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div id="map"></div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      demo.initGoogleMaps();
    });
  </script>
  
{% endblock javascripts %}

templates/home/ui-typography.html
{% extends "layouts/base.html" %}

{% block title %} UI Typography {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Material Dashboard Heading</h4>
              <p class="card-category">Created using Roboto Font Family</p>
            </div>
            <div class="card-body">
              <div id="typography">
                <div class="card-title">
                  <h2>Typography</h2>
                </div>
                <div class="row">
                  <div class="tim-typo">
                    <h1>
                      <span class="tim-note">Header 1</span>The Life of Material Dashboard </h1>
                  </div>
                  <div class="tim-typo">
                    <h2>
                      <span class="tim-note">Header 2</span>The Life of Material Dashboard</h2>
                  </div>
                  <div class="tim-typo">
                    <h3>
                      <span class="tim-note">Header 3</span>The Life of Material Dashboard</h3>
                  </div>
                  <div class="tim-typo">
                    <h4>
                      <span class="tim-note">Header 4</span>The Life of Material Dashboard</h4>
                  </div>
                  <div class="tim-typo">
                    <h5>
                      <span class="tim-note">Header 5</span>The Life of Material Dashboard</h5>
                  </div>
                  <div class="tim-typo">
                    <h6>
                      <span class="tim-note">Header 6</span>The Life of Material Dashboard</h6>
                  </div>
                  <div class="tim-typo">
                    <p>
                      <span class="tim-note">Paragraph</span>
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.</p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Quote</span>
                    <blockquote class="blockquote">
                      <p>
                        I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.
                      </p>
                      <small>
                        Kanye West, Musician
                      </small>
                    </blockquote>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Muted Text</span>
                    <p class="text-muted">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...
                    </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Primary Text</span>
                    <p class="text-primary">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Info Text</span>
                    <p class="text-info">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Success Text</span>
                    <p class="text-success">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Warning Text</span>
                    <p class="text-warning">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...
                    </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Danger Text</span>
                    <p class="text-danger">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
                  </div>
                  <div class="tim-typo">
                    <h2>
                      <span class="tim-note">Small Tag</span>
                      Header with small subtitle
                      <br>
                      <small>Use "small" tag for the headers</small>
                    </h2>
                  </div>
                </div>
              </div>
            </div>
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/violation_form.html
{% extends "layouts/base.html" %}

{% block title %}Violation Details{% endblock %}
{% load custom_filters %}

{% block content %}

<form method="post" action="{% url 'violation_form' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Violation Details</h4>
                    <p class="card-category">Complete the form with violation details</p>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="bmd-label-floating" for="id_date">Date of Violation</label>
                                {{ form.date|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="bmd-label-floating" for="id_violation_type">Violation Type</label>
                                {{ form.violation_type|add_class:"form-control" }}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="bmd-label-floating" for="id_fine_collected">Fine Collected</label>
                                {{ form.fine_collected|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="bmd-label-floating" for="id_vehicle_number">Vehicle Number</label>
                                {{ form.vehicle_number|add_class:"form-control" }}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <input type="text" name="officer_name" value="{{ form.officer_name.value }}" class="form-control" hidden>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating" for="id_description">Description</label>
                                {{ form.description|add_class:"form-control" }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="bmd-label-floating" for="id_image">Upload Violation Image</label>
                            <!-- Render the file input directly without using add_class -->
                            <input type="file" name="image" id="id_image" class="form-control">
                        </div>
                    </div>
                </div>


                    <button type="submit" class="btn btn-primary pull-right">Submit</button>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock content %}